name: urid
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-234.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  urid_logger:
    path: packages/urid_logger
  urid_api_client:
    path: packages/urid_api_client
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  intl: any
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  syncfusion_flutter_sliders: ^25.2.5
  clay_containers: ^0.3.4
  get_it: ^7.7.0
  sensors_plus: ^4.0.2
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  vibration: ^1.8.4
  volume_controller: ^2.0.7
  package_info_plus: any
  flutter_volume_controller: ^1.3.2
  uuid: any
  shared_preferences: ^2.2.3
  flutter_sound: any
  permission_handler: ^11.3.1
  audio_session: ^0.1.19
  path_provider: ^2.1.3
  csv: ^6.0.0
  flutter_email_sender: ^6.0.3
  video_player: ^2.8.6
  video_player_android: ^2.4.14
  pdf: ^3.10.8
  flutter_signature_pad: ^3.0.1
  flutter_pdfview: ^1.3.2
  printing: ^5.12.0
  open_file: ^3.3.2
  syncfusion_flutter_pdf: ^25.2.6
  syncfusion_flutter_signaturepad: ^25.2.6
  syncfusion_flutter_datagrid: ^25.2.6
  desktop_window: ^0.4.0
  mailer: ^6.1.0
  rounded_loading_button_plus: ^3.0.1
  roundcheckbox: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/animations/thanks.json
    - assets/animations/error.json
    - assets/videos/cover.mp4
    - assets/videos/flip.mp4
    - assets/videos/hold.mp4
    - assets/videos/volume.mp4
    - assets/pdf/consent.pdf

