name: urid
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-234.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  urid_logger:
    path: packages/urid_logger
  urid_api_client:
    path: packages/urid_api_client
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  intl: any
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  syncfusion_flutter_sliders: ^25.2.5
  clay_containers: ^0.3.4
  get_it: ^7.7.0
  sensors_plus: ^4.0.2
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  vibration: ^1.8.4
  volume_controller: ^2.0.7
  package_info_plus: any
  flutter_volume_controller: ^1.3.2
  uuid: any
  shared_preferences: ^2.2.3
  flutter_sound: any
  permission_handler: ^11.3.1
  audio_session: ^0.1.19
  path_provider: ^2.1.3
  csv: ^6.0.0
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/animations/study.json
    - assets/animations/break.json
    - assets/animations/coopWork.json
    - assets/animations/hello.json
    - assets/animations/privacy.json
    - assets/animations/interaction.json
    - assets/animations/start.json
    - assets/animations/survey.json
    - assets/animations/handCover.json
    - assets/animations/thanks.json
    - assets/animations/error.json

