name: urid_api_client
description: Package which manages client operations against the URID webservice.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  basic_utils: ^5.6.1
  http: ^1.0.0
  intl: any
  urid_logger:
    path: ../urid_logger
